### ISSUE TITLE
Alerts: prevent multiples of the same alert

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/alertinator#6]
We need a system so that a consistently failing condition does not trigger an alert every time it is ran.

If we are checking for error conditions and triggering alerts every 5 minutes, we do not necessarily want to receive the exact same alert every 5 minutes.

It needs to support:
- Customizable intervals
  - Notify me when the check fails, when it's been failing for at least 30min, 6hours, ... and when it stops.
- Be applied per (check-function, alert level) tuple
  - So as to ensure 5 repeated warnings from one function don't hide the 6th one which is critical
- Resetting counters for a given check after a successful run (Or X successful runs)
- Storing any state locally on the file-system in whatever format makes sense.

Imagined Interface as exposed to the rest of the system:

``` php
   // Returns [(bool)$shouldAlert, $firstAlertTimestamp];
   // $shouldAlert is true if an alert should be sent.
   // $firstAlertTimestamp is the unix timestamp of the first
   // occurrence of successive failures (or null if that info
   // is unavailable).
   // 
   // @param $isFailing -- bool indicating if the check is currently failing
   // @param $level -- string identifying alert level
   // @param $checkFunction -- string identifying check function
   protected function shouldAlert($isFailing, $level, $checkFunction);
```

The default implementation will be simply `return [$isFailing, null]`.

If `$shouldAlert` is true, the caller of this function will format a nice message using the `$firstAlertTimestamp`; something like "$alertMessage -- sustained for 30 minutes".

This code should live in a PHP Trait (the default implementation can be in the main class) so this trait can be included in a subclass if the user wants to utilize it.

There should be some unit tests to ensure it operates as expected.

**Comment by danielbeardsley** [comment]
Does this logic make sense? is this what we want? Should multiple `Notice` events eventually trigger a `Warning` so on up the chain?

**Comment by n-fisher** [comment]
@danielbeardsley #11 prevents multiples of the same alert by waiting on alerts till a threshold is reached, then alerting for every failure after that. Would it make more sense to alert after X failures, then every X failures after that so we don't have a repeated error blast alerts every time it fails after threshold X?

**Comment by danielbeardsley** [comment]
For sure. I'm OK with the delay X being the same as the mod X for simplicity. I'm also OK with them being separate values, but having the mod X default to the delay if unspecified.
